name: Build Production customer-service-bot

on:
  push:
    branches:
      - main
    paths:
      - customer-service-bot/**
      - infra/1-customer-bot/**
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

env:
  ACR_LOGIN_SERVER: int20h2026acrprod.azurecr.io
  IMAGE_NAME: customer-service-bot

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.meta.outputs.image }}

    steps:
      - uses: actions/checkout@v4

      # 1. Log into Azure
      - uses: azure/login@v1
        with:
          enable-oidc: true
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
      
       # 2. Log Docker into ACR
      - name: Login to ACR
        run: az acr login --name int20h2026acrprod

      # 3. Build and Push (Now this will work)
      - uses: docker/build-push-action@v5
        with:
          context: ./customer-service-bot
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: |
            ${{ env.ACR_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

      - id: meta
        run: echo "image=${{ env.IMAGE_NAME }}:${{ github.sha }}" >> $GITHUB_OUTPUT
